# Generated by Django 3.0.5 on 2020-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('yob', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('iscurrent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_data',
                'managed': False,
            },
        ),
    ]
