# Generated by Django 3.0.6 on 2020-05-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_players', '0003_auto_20200524_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersWKeepRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('iswk', models.IntegerField(default=0)),
                ('match_played', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('total_dismissals', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'players_wicket_keeping_records',
            },
        ),
    ]
