# Generated by Django 3.0.6 on 2020-05-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdiMatchScorecard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_code', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('notout', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField()),
                ('ballfaced', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('overs', models.FloatField()),
                ('maiden_overs', models.IntegerField()),
                ('runs_given', models.IntegerField()),
                ('wickets_taken', models.IntegerField()),
            ],
            options={
                'db_table': 'ODI_match_scorecard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdiMatchScorecardSerieswise',
            fields=[
                ('series_code', models.IntegerField(primary_key=True, serialize=False)),
                ('match_code', models.IntegerField(blank=True, null=True)),
                ('pcid', models.IntegerField(blank=True, null=True)),
                ('iscurrent', models.IntegerField(blank=True, null=True)),
                ('cname', models.TextField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('notout', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('ballfaced', models.IntegerField(blank=True, null=True)),
                ('fours', models.IntegerField(blank=True, null=True)),
                ('sixes', models.IntegerField(blank=True, null=True)),
                ('overs', models.IntegerField(blank=True, null=True)),
                ('maiden_overs', models.IntegerField(blank=True, null=True)),
                ('runs_given', models.IntegerField(blank=True, null=True)),
                ('wickets_taken', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ODI_match_scorecard_serieswise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdiSeriesRecord',
            fields=[
                ('series_code', models.IntegerField(primary_key=True, serialize=False)),
                ('cnt1', models.IntegerField()),
                ('cnt2', models.IntegerField()),
                ('matches', models.IntegerField()),
                ('cnt1_wins', models.IntegerField()),
                ('cnt2_wins', models.IntegerField()),
            ],
            options={
                'db_table': 'ODI_series_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateMatchScorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_code', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('outby', models.TextField()),
                ('notout', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('ballfaced', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('strikerate', models.FloatField()),
                ('overs', models.FloatField()),
                ('maiden_overs', models.IntegerField()),
                ('runs_given', models.IntegerField()),
                ('wickets_taken', models.IntegerField()),
                ('noballs', models.IntegerField()),
                ('wideballs', models.IntegerField()),
            ],
            options={
                'db_table': 'state_match_scorecard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateMatchScorecardSerieswise',
            fields=[
                ('series_code', models.IntegerField(primary_key=True, serialize=False)),
                ('match_code', models.IntegerField(blank=True, null=True)),
                ('team', models.TextField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('notout', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('ballfaced', models.IntegerField(blank=True, null=True)),
                ('fours', models.IntegerField(blank=True, null=True)),
                ('sixes', models.IntegerField(blank=True, null=True)),
                ('overs', models.FloatField(blank=True, null=True)),
                ('maiden_overs', models.IntegerField(blank=True, null=True)),
                ('runs_given', models.IntegerField(blank=True, null=True)),
                ('wickets_taken', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'state_match_scorecard_serieswise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateSeriesRecord',
            fields=[
                ('series_code', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'state_series_record',
                'managed': False,
            },
        ),
    ]
