# Generated by Django 3.0.5 on 2020-05-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.TextField()),
                ('img_url', models.ImageField(default='teams/India.jpg', upload_to='teams')),
            ],
            options={
                'db_table': 'country_data',
                'managed': False,
            },
        ),
    ]
