# Generated by Django 3.0.5 on 2020-05-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'managed': False},
        ),
    ]
